### ISSUE TITLE
README.ru.md сделать на русском языке....

### ISSUE THREAD

**Issue by conrad66** [alryaz/hass-mosenergosbyt#2]
Если есть файл README.ru.md, возможно ли его сделать на русском ?

p.s. Автору конечно виднее ...
Но зачем вообще такое подробное описание на английском и такое "урезанное" на русском ?
Есть ли статистика кто из англоговорящих людей пользуется Мосэнергосбыт`ом ?

**Comment by alryaz** [comment]
Не заметил ваш Issue до этого, но сегодняшние коммиты должны были перевести большую часть, и перенести в [README.md](https://github.com/alryaz/hass-mosenergosbyt/blob/master/README.md). Предыдущий README.ru случайно утёк вместе с изменениями в оригинальный README.

С Вашей позицией полностью согласен, однако привык изначально писать на английском. Английское описание останется в README.en.md.

Если имеются замечания, я готов выслушать предложения. Осталось перенести текст в info.md, над этим работаю.

**Comment by conrad66** [comment]
Спасибо что быстро откликнулись. Замечания были только в оформлении ))
