### ISSUE TITLE
Просьба обновить документацию по обработке событий

### ISSUE THREAD

**Issue by Spirituss** [alryaz/hass-mosenergosbyt#4]
Документация не полная:
1) В документации в одном месте название события от вызова службы описано как mosenergosbyt_calculation_result, но в примере кода - уже как  event_type: calculation_result - какое имя правильное?
2) Не указано наименование события при ответе на вызов службы mosenergosbyt.push_indications - перебрал несколько вариантов, ничего не подошло.

**Comment by alryaz** [comment]
1. `mosenergosbyt_calculation_result` - правильное название события; поправил в документации, благодарю за замечание
2. `mosenergosbyt_push_result` - название события, приходящего после передачи показаний

Изменения в коммите 30b25c8b1bb1387620aa2277ef022a928763e029 , скоро будет релизная версия
