### ISSUE TITLE
Нет настроек, если добавлял через интеграции

### ISSUE THREAD

**Issue by Siorinex** [alryaz/hass-mosenergosbyt#7]
При добавлении через интеграции - невозможно задать периоды обновления и т.д.: если внести их в конфиг без логина пароля - ругается, а если с логином и паролем - зачем тогда интеграция нужна?

**Comment by alryaz** [comment]
Древний issue, но в нынешнем релизе (v0.3.0) добавлены опции (как раз таки для меню "Интеграции")
