### ISSUE TITLE
Ошибка в документации mosenergosbyt.push_indications

### ISSUE THREAD

**Issue by Spirituss** [alryaz/hass-mosenergosbyt#9]
В документации на метод ```mosenergosbyt.push_indications``` указано:
<img width="659" alt="Снимок экрана 2020-10-20 в 13 02 26" src="https://user-images.githubusercontent.com/47206760/96571673-8cd3f580-12d4-11eb-87df-1b51aefba5c5.png">

Но метод принимает только целочисленные значения показаний.

**Comment by alryaz** [comment]
Принято в работу

**Comment by alryaz** [comment]
Ошибка обнаружена (только целочисленные значения в валидаторе, действительно), будет исправлена сегодня.

**Comment by alryaz** [comment]
@Spirituss пожалуйста, протестируйте передачу на версии master из HACS. У меня пока период передачи неактивен, форсировать передачу не могу пока что.

**Comment by Spirituss** [comment]
@alryaz Если за октябрь уже передавал, повторно не смогу?

**Comment by Spirituss** [comment]
Работает.
